### ISSUE TITLE
RSS: autobrr doesn't read the whole description

### ISSUE THREAD

**Issue by DigitGram** [autobrr/autobrr#1766]
**Version**
v1.47.1

**Describe the bug**
I have an RSS indexer, where the whole NFO of an release is in its description-section.
According to log autobrr only reads the first 990 characters of the description, therefore my filter (looking for a specific genre) is not applied.

**To Reproduce**
see log-entry:
`{"level":"debug","module":"filter","method":"CheckFilter","time":"2024-10-13T12:07:12+02:00","message":"(<CENSORED>) for release: <CENSORED> rejections: (match description not matching. got: Kategori: Music \n Storlek: 87.37 MiB\n                                        ?                               T O T E N K V L T                                       ?                                        ??                                         ??                                       ?  ??                                       ?  ??                        ?                                       ?  ???                        ?                                       ?  ???                       ???                                       ?   ?? ?                     ?? ??       ?                               ?   ??  ?   ??           ?  ?????       ??  ?              ?  ??       ?   ??? ?????   ??  ???      ????        ???                ???        ?   ?? ????      ????       ????        ????               ????        ?    ??  ????    ??  ?       ?????        ????                ???        ?     ?? ?????         ?     ?????        ????            ??  ???        ? ?????? ??)"}
`

**Expected behavior**
autobrr should read the whole "description"-section in my rss-feed.
It used to work with future versions! (last working: v1.46)

**Desktop (please complete the following information):**
 - OS: Docker compose @ Synology NAS DS920+

**Additional context**
Any infos, whats going on here? Maybe something changed with a newer release?

**Comment by zze0s** [comment]
Hi! For performance reasons we cut the logs at 1024 bytes/characters but it still parses and tries to read the whole description if provided.

It does make debugging a bit harder but without the truncating it would fill the log files to quickly if you parse a feed of 10-100 of those items.

If you have examples of it not matching when it should then there might be a bug here or your filter is not correct.

Can you share your values for `Match Description` and a part of the description it should have matched so we can look for any issues?

**Comment by DigitGram** [comment]
Thanks for info.

Here I got an example, where it did not fetch the release, whereas prior versions of autobrr just worked fine:
[rss-feed.txt](https://github.com/user-attachments/files/17416806/rss-feed.txt)
[new_autobrr.log](https://github.com/user-attachments/files/17416807/new_autobrr.log)

My filter:
![Image](https://github.com/user-attachments/assets/a5ca1433-869f-4e16-94b2-27f46ebca531)

I didn't change anything. System was working until autobrr got auto-updated on my system to v1.47.1. Latest working version was v1.46 on my system.

If you need further infos, don't hesitate to contact me. Thanks!

**Comment by DigitGram** [comment]
I played around a bit and found this out. If you remove the asterisk and the question mark, it works again.

Filter "match description":
old: *black?metal*
>>> NOT WORKING

new: black metal
>>> WORKING

**Comment by zze0s** [comment]
I played around with this yesterday and had it matching with your initial examples as expected so not sure what's up. One big problem is however that the full rejections string gets truncated instead of just some values, so I'm working on a PR to improve that so it's more readable.

**Comment by zze0s** [comment]
@DigitGram we just released v1.48.0 which have some fixes for filtering and refactored rejections so they will show more info now. On log level Trace it will show the full data like the description. On Debug it will truncate it.

Please update and get back if you have further issues.

**Comment by DigitGram** [comment]
Thanks for quick update. I will test it and report back!

**Comment by DigitGram** [comment]
autobrr: deleted config, reinstalled container completely, and reconfigured it again with v1.48.0
Filter still not working. See log

`*black?metal* < NOT working
black metal < working!`

[[trace-autobrr.log](https://github.com/user-attachments/files/17477578/trace-autobrr.log)
](url)

**Comment by zze0s** [comment]
Was finally able to reproduce this bug. We'll start working on a fix.

**Comment by DigitGram** [comment]
Thank you for all your work, @zze0s and rest of staff.

Glad, that I could help a little. :-)

**Comment by DigitGram** [comment]
![Image](https://github.com/user-attachments/assets/d01e4c67-30fa-4979-b8b8-64b588db68ec)
Running. Will report back, as soon as filter is activated.

**Comment by DigitGram** [comment]
> [@DigitGram](https://github.com/DigitGram) Appreciate it! Can you test this image tag `pr-1780` once it's built in a couple of minutes?

`pr-1780` is working.
Match description: `*black?metal*` works again as expected. Thanks!!

See example in .log
[trace-autobrr.log](https://github.com/user-attachments/files/17491164/trace-autobrr.log)

**Comment by zze0s** [comment]
Great! Will get it merged ASAP. Would advice to stay on that tag until we release a new version in the coming days 👍
